Opened a File for Reading
1.	The "pass" statement in python does nothing. Instead, it normally
	functions as a placeholder for things you want to do in the future. For
	example, after we've opened the file, we want to do things with it, but
	we currently haven't gotten that far. If we left the line blank, we
	would get the error

		  File "./word_counter.py", line 7
		    return word_counts
		         ^
		IndentationError: expected an indented block

	since anything after a line ending in a colon must be indented and have
	at least one statement.
2.	"as" lets you call or rename whatever is on the left of it to whatever
	is on the right of it in this case, it will allow us to rename the
	output of 'open(filename, "r")' to "reader".
3.	"with" statements in python take the form

		with _________ as _________:

	where the first blank is something you want to set up and the second
	blank is what you want to call it. When you open a file, programs need
	to allocate new memory to store the contents and some metadata about the
	file. Furthermore, like most, if not all, other programming languages,
	python cannot figure out when you're done with the file unless you tell
	it explicitly. As you can imagine, there is a function in python that
	can close a file. Runtime errors and exceptions can stop your program
	from running before it gets to close the file, so you would have to
	write some code to catch all exceptions and write a ton of boilerplate
	whenever you wanted to open a file. To circumvent this, the people
	behind python added the with statement, which will handle catching the
	exceptions and cleaning everything up for you automatically. If you want
	to read more, check out
	https://effbot.org/zone/python-with-statement.htm for more information.
4.	The "open" function in python takes in two parameters, the file that
	you want to interact with and how you want to interact with it. We
	just want to read the file, so we give it the string "r". If we wanted
	to write to the file, we would give it "w". If we wanted to append to
	the end of the file, we would give it "a".
5.	Strings in python are denoted with either surrounding single quotes,
	double quotes, three single quotes, or three double quotes, and you
	choose the one that fits the string.